### ISSUE TITLE
Discord websocket close sent issue

### ISSUE THREAD

**Issue by kod570** [Crypto90/TS3MusicBot-Pterodactyl-Egg#1]
Hey Crypto90 i have an issue mayby it can be fixed form you experience.

The issue is Discord i Closing the Voice many times a day 
Here is my issue and i can't figure it out.
voice.go:604:wsHeartbeat() error sending heartbeat to voice endpoint rotterdam3563.discord.media:443, websocket: close sent

Best Regards kod570

**Comment by Crypto90** [comment]
Discord is closing it’s server on their server side.
There is nothing we can do about it on client side, other than doing a reconnect to a new node.

discord is doing this on purpose.

**Comment by Crypto90** [comment]
This also happens based on the load discord has in a region. You can try do change the voice channel region, which could make the reconnects (server shutdowns) less frequent.

**Comment by kod570** [comment]
Hello again Crypto90

i havent seen you have types to written to me before now 

but i have get som fixes yester days form ts3musicbot.net support 

So now they have fixed the problem 100%. 

So your are wellcome to close this issue

Best regards kod570
